version: "3"

networks:
  hamidgram:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - hamidgram
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql 5.7.22
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - hamidgram
    volumes:
      - ./mysql:/var/lib/mysql
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hamidgram
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - SERVICE_TAG=dev
      - SERVICE_NAME=mysql
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: php
    ports:
      - "9000:9000"
    networks:
      - hamidgram
    volumes:
      - ./src:/var/www/html
  redis:
    image: redis:6.0.6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hamidgram
    volumes:
      - ./redis:/data
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  artisan:
    build:
      context: .
      dockerfile: DockerFile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      - hamidgram
